// =============================================================================
// Application Configuration
// =============================================================================
//
// All tuneable constants live here so they can be changed in one place.
// In a real deployment you would inject these at build time via Vite's
// `import.meta.env` mechanism (environment variables prefixed with VITE_).
// =============================================================================

/**
 * The URL passed to `Moq.Connection.connect()`.
 *
 * HOW THE URL IS INTERPRETED BY @moq/lite:
 *
 *   http://host:port  →  insecure local-dev mode
 *     1. @moq/lite fetches the relay's TLS fingerprint from
 *        http://host:port/certificate.sha256 (plain HTTP, TCP).
 *     2. It then opens a WebTransport connection to
 *        https://host:port, passing the fingerprint as
 *        `serverCertificateHashes` so the browser trusts the
 *        self-signed certificate without a CA.
 *     3. If WebTransport is unavailable (or loses the race),
 *        it falls back to a WebSocket at ws://host:port.
 *
 *   https://host:port →  production mode (CA-signed cert required)
 *     Direct WebTransport / WebSocket over TLS.
 *
 * For the Docker dev environment we use http:// so the self-signed cert
 * generated by `--tls-generate localhost` is trusted automatically.
 */
export const RELAY_URL: string = "http://localhost:4443";

/**
 * MoQ broadcast path prefix for all chat traffic.
 *
 * Path layout inside the relay's namespace:
 *
 *   moq-chat/{roomId}/{username}     ← each user's personal broadcast
 *     └── track "typing"             ← live keystroke-by-keystroke text
 *     └── track "messages"           ← confirmed, sent messages
 *
 * The relay stores any broadcast that any publisher announces.
 * Subscribers discover active users via `connection.announced()` using the
 * room prefix `moq-chat/{roomId}/`.
 */
export const MOQ_PATH_PREFIX = "moq-chat";

/**
 * Name of the MoQ track that carries live typing state.
 *
 * Each group on this track contains a single JSON frame with the
 * full current text of what the user is typing.  Old groups are
 * discarded automatically by @moq/lite so subscribers always see
 * the latest text without replaying history.
 */
export const TRACK_TYPING = "typing";

/**
 * Name of the MoQ track that carries sent (committed) messages.
 *
 * Each group carries a single JSON frame with the final message text
 * and a timestamp.  Unlike the typing track, message groups accumulate
 * so the full conversation history is preserved for the session.
 */
export const TRACK_MESSAGES = "messages";

/**
 * Priority assigned to both tracks when subscribing.
 *
 * Lower numbers = higher priority in QUIC stream scheduling.
 * We give both tracks the same priority for this demo.  In a real
 * application you might give typing updates higher priority (lower value)
 * than message history so the live-typing UI feels snappier.
 */
export const TRACK_PRIORITY = 0;
